[tendermint]
http_rpc_url = "https://testnet-croeseid-1.crypto.com:26657"

[database]
host = "localhost"
port = 5432
username = "postgres"
# password can only be provided through Environment variable `DB_PASS`
name = "postgres"
schema = "public"
ssl = true

[postgres]
pool_max_conns = 4
pool_min_conns = 0
pool_max_conn_lifetime = "1h"
pool_max_conn_idle_time = "30m"
pool_health_check_interval = "1m"